<?php

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ProductsTest extends WebTestCase
{

    private $client;

    protected function setUp(): void
    {
        $this->client = static::createClient();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @Test */
    public function testCreateProduct() {

            $product = [
                "name" => "Test Produkt",
                "price" => 20.5
            ];

            $this->client->request('POST', '/api/v1/product', [], [], array('CONTENT_TYPE' => 'application/json'), json_encode($product));

            $this->assertEquals(201, $this->client->getResponse()->getStatusCode());

    }


    /** @Test */
    public function testUpdateProduct() {

        $product = [
            "id" => 1,
            "name" => "Test Produkt-2",
            "price" => 22.0
        ];

        $this->client->request('PUT', '/api/v1/product', [], [], array('CONTENT_TYPE' => 'application/json'), json_encode($product));

        $this->assertEquals(202, $this->client->getResponse()->getStatusCode());

    }

    /** @Test */
    public function testDeleteProduct() {

        $product = [
            "id" => 1,
            "name" => "Test Produkt-2",
            "price" => 22.0
        ];

        $this->client->request('DELETE', '/api/v1/product/1', [], [], array('CONTENT_TYPE' => 'application/json'), json_encode($product));

        $this->assertEquals(200, $this->client->getResponse()->getStatusCode());

    }


}